package emitgo

import (
	"fmt"
	"go/format"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/DeanoC/mister-packages/internal/pack"
)

func GenerateSystem(sys *pack.SystemFile) (string, error) {
	index, hasCartridge := cartridgeIndex(sys)
	prefix := exportedIdent(sys.ExpectedCore)
	if prefix == "" {
		return "", fmt.Errorf("expected_core %q is not a Go identifier", sys.ExpectedCore)
	}
	var b strings.Builder
	b.WriteString("// Code generated by mister-packages from packages/system/")
	b.WriteString(sys.ID)
	b.WriteString(".yaml.\n")
	b.WriteString("// Do not edit.\n")
	if hasCartridge {
		b.WriteString("// FogCast launch fields: expected core and cartridge file index.\n")
	} else {
		b.WriteString("// FogCast launch fields: system and expected core identity.\n")
	}
	b.WriteString("// Product fields (aliases, covers, Main RBF path, library roots) stay in FogCast.\n\n")
	b.WriteString("package generated\n\n")
	b.WriteString("const (\n")
	fmt.Fprintf(&b, "\t%sSystem = %q\n", prefix, sys.ID)
	fmt.Fprintf(&b, "\t%sExpectedCore = %q\n", prefix, sys.ExpectedCore)
	if hasCartridge {
		fmt.Fprintf(&b, "\t%sCartridgeIndex = %d\n", prefix, index)
	}
	b.WriteString(")\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gofmt: %w", err)
	}
	return string(formatted), nil
}

// GenerateABI emits package constants for host-side consumers. Target runtime
// builds use the C++ emitter instead of invoking this Go code.
func GenerateABI(abi *pack.ABIFile) (string, error) {
	if err := abi.Validate(); err != nil {
		return "", err
	}
	if err := validateABISymbols(abi); err != nil {
		return "", err
	}
	prefix := abiGoPrefix(abi)
	var b strings.Builder
	b.WriteString("// Code generated by mister-packages from packages/abi/")
	b.WriteString(goPackageFileName(abi.ID))
	b.WriteString(".yaml.\n// Do not edit.\n\npackage generated\n\nconst (\n")
	fmt.Fprintf(&b, "\t%sABIID = %q\n", prefix, abi.ID)
	fmt.Fprintf(&b, "\t%sABIMajor uint16 = %d\n", prefix, abi.Major)
	fmt.Fprintf(&b, "\t%sABIMinor uint16 = %d\n", prefix, abi.Minor)
	fmt.Fprintf(&b, "\t%sABITag uint16 = %d\n", prefix, abi.Tag)
	for _, constant := range abi.Constants {
		fmt.Fprintf(&b, "\t%s uint32 = 0x%x\n", constant.Name, uint64(constant.Value))
	}
	for _, iface := range abi.Interfaces {
		suffix := abiGoInterfaceSuffix(iface.ID)
		fmt.Fprintf(&b, "\t%sInterface%sID = %q\n", prefix, suffix, iface.ID)
		fmt.Fprintf(&b, "\t%sInterface%sMajor uint16 = %d\n", prefix, suffix, iface.Major)
		fmt.Fprintf(&b, "\t%sInterface%sMinor uint16 = %d\n", prefix, suffix, iface.Minor)
		fmt.Fprintf(&b, "\t%sCapability%s uint32 = 0x%x\n", prefix, suffix, uint32(1)<<iface.CapabilityBit)
	}
	b.WriteString(")\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gofmt: %w", err)
	}
	return string(formatted), nil
}

func validateABISymbols(abi *pack.ABIFile) error {
	prefix := abiGoPrefix(abi)
	seen := map[string]bool{}
	add := func(name string) error {
		if seen[name] {
			return fmt.Errorf("ABI %q generates duplicate Go symbol %q", abi.ID, name)
		}
		seen[name] = true
		return nil
	}
	for _, name := range []string{prefix + "ABIID", prefix + "ABIMajor", prefix + "ABIMinor", prefix + "ABITag"} {
		if err := add(name); err != nil {
			return err
		}
	}
	for _, constant := range abi.Constants {
		if err := add(constant.Name); err != nil {
			return err
		}
	}
	for _, iface := range abi.Interfaces {
		suffix := abiGoInterfaceSuffix(iface.ID)
		for _, name := range []string{prefix + "Interface" + suffix + "ID", prefix + "Interface" + suffix + "Major", prefix + "Interface" + suffix + "Minor", prefix + "Capability" + suffix} {
			if err := add(name); err != nil {
				return err
			}
		}
	}
	return nil
}

// GenerateProgrammingProfiles emits the platform's approved profile/ABI-major
// rows. Diagnostic-only rows intentionally retain an empty ABI and major zero.
func GenerateProgrammingProfiles(profiles *pack.ProgrammingProfilesFile) (string, error) {
	if err := profiles.Validate(); err != nil {
		return "", err
	}
	prefix := exportedIdent(profiles.Platform)
	var b strings.Builder
	b.WriteString("// Code generated by mister-packages from packages/programming/")
	b.WriteString(goPackageFileName(profiles.ID))
	b.WriteString(".yaml.\n// Do not edit.\n\npackage generated\n\n")
	b.WriteString("const (\n")
	fmt.Fprintf(&b, "\t%sProgrammingPlatform = %q\n", prefix, profiles.Platform)
	fmt.Fprintf(&b, "\t%sProgrammingDevice = %q\n", prefix, profiles.Device)
	b.WriteString(")\n\n")
	b.WriteString("type ProgrammingProfilePair struct {\n\tProfile string\n\tABI string\n\tMajor uint16\n\tDiagnosticOnly bool\n}\n\n")
	fmt.Fprintf(&b, "var %sProgrammingProfilePairs = []ProgrammingProfilePair{\n", prefix)
	for _, profile := range profiles.Profiles {
		if profile.DiagnosticOnly {
			fmt.Fprintf(&b, "\t{Profile: %q, DiagnosticOnly: true},\n", profile.ID)
			continue
		}
		for _, abi := range profile.ABIs {
			fmt.Fprintf(&b, "\t{Profile: %q, ABI: %q, Major: %d},\n", profile.ID, abi.ID, abi.Major)
		}
	}
	b.WriteString("}\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gofmt: %w", err)
	}
	return string(formatted), nil
}

func cartridgeIndex(sys *pack.SystemFile) (int, bool) {
	for _, rule := range sys.Media {
		if rule.Role == "cartridge" {
			return rule.Index, true
		}
	}
	return 0, false
}

func exportedIdent(value string) string {
	var b strings.Builder
	start := true
	for _, r := range value {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			start = true
			continue
		}
		if start {
			start = false
			if unicode.IsLetter(r) {
				r = unicode.ToUpper(r)
			}
		}
		b.WriteRune(r)
	}
	s := b.String()
	first, _ := utf8.DecodeRuneInString(s)
	if s == "" || !unicode.IsLetter(first) {
		return ""
	}
	return s
}

func abiGoPrefix(abi *pack.ABIFile) string {
	if abi.ID == "fes.simple-game" {
		return "FesGp"
	}
	return exportedIdent(abi.ID)
}

func abiGoInterfaceSuffix(id string) string {
	return exportedIdent(strings.TrimPrefix(id, "fes."))
}

func goPackageFileName(id string) string {
	return strings.NewReplacer(".", "_", "-", "_", "/", "_").Replace(id)
}
