package emitgo

import (
	"fmt"
	"go/format"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/DeanoC/mister-packages/internal/pack"
)

func GenerateSystem(sys *pack.SystemFile) (string, error) {
	index, err := cartridgeIndex(sys)
	if err != nil {
		return "", err
	}
	prefix := exportedIdent(sys.ExpectedCore)
	if prefix == "" {
		return "", fmt.Errorf("expected_core %q is not a Go identifier", sys.ExpectedCore)
	}
	var b strings.Builder
	b.WriteString("// Code generated by mister-packages from packages/system/")
	b.WriteString(sys.ID)
	b.WriteString(".yaml.\n")
	b.WriteString("// Do not edit.\n")
	b.WriteString("// FogCast launch fields: expected core and cartridge file index.\n")
	b.WriteString("// Product fields (aliases, covers, Main RBF path, library roots) stay in FogCast.\n\n")
	b.WriteString("package generated\n\n")
	b.WriteString("const (\n")
	fmt.Fprintf(&b, "\t%sSystem = %q\n", prefix, sys.ID)
	fmt.Fprintf(&b, "\t%sExpectedCore = %q\n", prefix, sys.ExpectedCore)
	fmt.Fprintf(&b, "\t%sCartridgeIndex = %d\n", prefix, index)
	b.WriteString(")\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gofmt: %w", err)
	}
	return string(formatted), nil
}

func cartridgeIndex(sys *pack.SystemFile) (int, error) {
	for _, rule := range sys.Media {
		if rule.Role == "cartridge" {
			return rule.Index, nil
		}
	}
	return 0, fmt.Errorf("system %s: missing cartridge media", sys.ID)
}

func exportedIdent(value string) string {
	var b strings.Builder
	start := true
	for _, r := range value {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			start = true
			continue
		}
		if start {
			start = false
			if unicode.IsLetter(r) {
				r = unicode.ToUpper(r)
			}
		}
		b.WriteRune(r)
	}
	s := b.String()
	first, _ := utf8.DecodeRuneInString(s)
	if s == "" || !unicode.IsLetter(first) {
		return ""
	}
	return s
}
