// Package emitverilog emits synthesis-compatible constant includes. It does
// not generate modules, netlists, constraints, or programming recipes.
package emitverilog

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/DeanoC/mister-packages/internal/pack"
)

// GenerateABI emits a guarded Verilog include of unsigned 32-bit ABI constants.
func GenerateABI(abi *pack.ABIFile) (string, error) {
	if err := abi.Validate(); err != nil {
		return "", err
	}
	if err := validateABIMacros(abi); err != nil {
		return "", err
	}
	prefix := verilogPrefix(abi)
	guard := prefix + "_CONSTANTS_V1"
	var b strings.Builder
	b.WriteString("// Code generated by mister-packages from packages/abi/")
	b.WriteString(packageFileName(abi.ID))
	b.WriteString(".yaml. Do not edit.\n")
	fmt.Fprintf(&b, "`ifndef %s\n`define %s\n\n", guard, guard)
	for _, constant := range abi.Constants {
		fmt.Fprintf(&b, "`define %s 32'h%08x\n", verilogConstantName(constant.Name), uint64(constant.Value))
	}
	for _, iface := range abi.Interfaces {
		name := prefix + "_INTERFACE_" + verilogInterfaceName(iface.ID)
		fmt.Fprintf(&b, "`define %s_MAJOR 32'h%08x\n", name, iface.Major)
		fmt.Fprintf(&b, "`define %s_MINOR 32'h%08x\n", name, iface.Minor)
		fmt.Fprintf(&b, "`define %s_CAPABILITY_BIT 32'h%08x\n", name, iface.CapabilityBit)
		fmt.Fprintf(&b, "`define %s_CAPABILITY_MASK 32'h%08x\n", name, uint32(1)<<iface.CapabilityBit)
	}
	fmt.Fprintf(&b, "\n`endif // %s\n", guard)
	return b.String(), nil
}

func validateABIMacros(abi *pack.ABIFile) error {
	prefix := verilogPrefix(abi)
	seen := map[string]bool{prefix + "_CONSTANTS_V1": true}
	add := func(name string) error {
		if seen[name] {
			return fmt.Errorf("ABI %q generates duplicate Verilog macro %q", abi.ID, name)
		}
		seen[name] = true
		return nil
	}
	for _, constant := range abi.Constants {
		if err := add(verilogConstantName(constant.Name)); err != nil {
			return err
		}
	}
	for _, iface := range abi.Interfaces {
		name := prefix + "_INTERFACE_" + verilogInterfaceName(iface.ID)
		for _, suffix := range []string{"_MAJOR", "_MINOR", "_CAPABILITY_BIT", "_CAPABILITY_MASK"} {
			if err := add(name + suffix); err != nil {
				return err
			}
		}
	}
	return nil
}

func verilogPrefix(abi *pack.ABIFile) string {
	if abi.ID == "fes.simple-game" {
		return "FES_GP"
	}
	return strings.ToUpper(strings.NewReplacer(".", "_", "-", "_", "/", "_").Replace(abi.ID))
}

func verilogConstantName(name string) string {
	var b strings.Builder
	for i, r := range name {
		if i > 0 && unicode.IsUpper(r) {
			previous := rune(name[i-1])
			if unicode.IsLower(previous) || unicode.IsDigit(previous) {
				b.WriteByte('_')
			}
		}
		b.WriteRune(unicode.ToUpper(r))
	}
	return b.String()
}

func verilogInterfaceName(id string) string {
	id = strings.TrimPrefix(id, "fes.")
	return strings.ToUpper(strings.NewReplacer(".", "_", "-", "_", "/", "_").Replace(id))
}

func packageFileName(id string) string {
	return strings.NewReplacer(".", "_", "-", "_", "/", "_").Replace(id)
}
