# SPDX-License-Identifier: GPL-2.0-or-later
"""Host-only instruction/trap and independent FAT12 checks for original PRG."""

import contextlib
import hashlib
import io
import json
from pathlib import Path
import struct
import tempfile
import unittest

from scripts import atari_st_disk_diagnostic as diagnostic


class Machine:
    """Independent decoder for the PRG's bounded 68000 ISA, with GEMDOS stub.

    Decodes generated bytes, not emitter labels. Trap #1 reads the actual stack
    and clobbers volatile registers. This is not an EmuTOS filesystem emulator.
    """

    def __init__(self, failure=None, base=0x4000):
        prg = diagnostic.build_prg()
        header = struct.unpack_from(">H6IH", prg)
        assert header == (0x601a, len(prg) - 28, 0, 0, 0, 0, 0, 1)
        self.memory = bytearray(0x80000)
        self.memory[base:base + header[1]] = prg[28:]
        self.d, self.a = [0] * 8, [0] * 8
        self.a[7] = 0x70000
        struct.pack_into(">I", self.memory, self.a[7] + 4, base - 256)
        self.base, self.stack_end = base, base + header[1]
        self.pc = base
        self.z = self.n = False
        self.files = {"A:\\PASS.TXT": b"stale pass", "A:\\FAIL.TXT": b"stale fail"}
        self.handles, self.calls, self.console = {}, [], []
        self.exit = None
        self.failure = failure
        self.injected = False

    def integer(self, address, size):
        return int.from_bytes(self.memory[address:address + size], "big")

    def fetch(self, size=2):
        value = self.integer(self.pc, size)
        self.pc += size
        return value

    def signed_word(self):
        value = self.fetch()
        return value - 0x10000 if value & 0x8000 else value

    def push(self, value, size):
        self.a[7] -= size
        self.memory[self.a[7]:self.a[7] + size] = (value & ((1 << (size * 8)) - 1)).to_bytes(size, "big")

    def text(self, address):
        end = self.memory.index(0, address)
        return self.memory[address:end].decode("ascii")

    def flags(self, value, bits):
        value &= (1 << bits) - 1
        self.z, self.n = value == 0, bool(value & (1 << (bits - 1)))

    def trap(self):
        stack = self.a[7]
        function = self.integer(stack, 2)
        arg = lambda offset, size: self.integer(stack + 2 + offset, size)
        name, result = None, 0
        if function in (0x3c, 0x3d, 0x41):
            name = self.text(arg(0, 4))
            assert name.startswith("A:\\")
        elif function in (0x3e, 0x3f, 0x40):
            handle = arg(0, 2)
            name = self.handles.get(handle, [None])[0]
        self.calls.append((function, name))
        should_fail = (self.failure == (function, name) and not self.injected and
                       (function != 0x41 or name in self.files))
        if should_fail:
            self.injected = True
            result = -36
        elif function == 0x3c:
            assert arg(4, 2) == 0
            self.files[name] = b""
            handle = max(self.handles, default=5) + 1
            self.handles[handle] = [name, 0]
            result = handle
        elif function == 0x3d:
            assert arg(4, 2) == 0
            if name not in self.files:
                result = -33
            else:
                handle = max(self.handles, default=5) + 1
                self.handles[handle] = [name, 0]
                result = handle
        elif function == 0x3e:
            if handle not in self.handles:
                result = -37
            else:
                del self.handles[handle]
                if self.failure == "trailing byte" and name == "A:\\FESDATA.TMP" and not self.injected:
                    self.files[name] += b"!"
                    self.injected = True
        elif function in (0x3f, 0x40):
            assert handle in self.handles
            count, pointer = arg(2, 4), arg(6, 4)
            assert 0 < count < 16384
            assert 0 < pointer < len(self.memory) - count
            position = self.handles[handle][1]
            if function == 0x40:
                data = bytes(self.memory[pointer:pointer + count])
                if self.failure == "short write" and name == "A:\\FESDATA.TMP" and not self.injected:
                    data = data[:-1]
                    self.injected = True
                original = self.files[name]
                self.files[name] = original[:position] + data + original[position + len(data):]
            else:
                data = self.files[name][position:position + count]
                if name == "A:\\FESDATA.TMP" and not self.injected:
                    if self.failure == "short read":
                        data = data[:-1]
                        self.injected = True
                    elif self.failure == "corrupt read":
                        data = data[:1024] + bytes([data[1024] ^ 0x80]) + data[1025:]
                        self.injected = True
                self.memory[pointer:pointer + len(data)] = data
            result = len(data)
            self.handles[handle][1] += result
        elif function == 0x41:
            if name in self.files:
                assert all(info[0] != name for info in self.handles.values()), "deleting an open file"
                del self.files[name]
            else:
                result = -33
        elif function == 0x56:
            assert arg(0, 2) == 0
            old, new = self.text(arg(2, 4)), self.text(arg(6, 4))
            if self.failure == "rename":
                result, self.injected = -36, True
            else:
                assert old in self.files and new not in self.files
                self.files[new] = self.files.pop(old)
        elif function == 0x09:
            self.console.append(self.text(arg(0, 4)))
        elif function == 0x4a:
            assert arg(0, 2) == 0
            assert arg(2, 4) == self.base - 256
            assert arg(6, 4) == self.stack_end - self.base + 256
            assert stack == self.stack_end - 12, "Mshrink stack not retained"
        elif function == 0x4c:
            assert stack == self.stack_end - 4, "unbalanced GEMDOS argument stack"
            self.exit = arg(0, 2)
            self.handles.clear()  # Pterm closes process files
        else:
            raise AssertionError(f"unexpected GEMDOS function {function:02x}")
        self.d[0] = result & 0xffffffff
        for register in (1, 2):
            self.d[register], self.a[register - 1] = 0xdeadbeef, 0xdeadbeef

    def run(self):
        for _ in range(25000):
            instruction = self.fetch()
            if instruction & 0xf1ff == 0x41fa:  # LEA d16(PC),An
                base = self.pc
                self.a[(instruction >> 9) & 7] = base + self.signed_word()
            elif instruction == 0x4fef:  # LEA d16(SP),SP
                self.a[7] += self.signed_word()
            elif instruction == 0x286f:  # MOVEA.L d16(SP),A4
                self.a[4] = self.integer(self.a[7] + self.signed_word(), 4)
            elif instruction == 0x3f3c:
                self.push(self.fetch(), 2)
            elif instruction == 0x2f3c:
                self.push(self.fetch(4), 4)
            elif instruction & 0xfff8 == 0x2f08:
                self.push(self.a[instruction & 7], 4)
            elif instruction == 0x3f06:
                self.push(self.d[6], 2)
            elif instruction == 0x2c00:
                self.d[6] = self.d[0]
            elif instruction & 0xf100 == 0x7000:
                value = instruction & 0xff
                self.d[(instruction >> 9) & 7] = (value - 256 if value & 128 else value) & 0xffffffff
                self.flags(value, 8)
            elif instruction & 0xfff8 == 0x4a80:
                self.flags(self.d[instruction & 7], 32)
            elif instruction == 0x0c80:
                self.flags(self.d[0] - self.fetch(4), 32)
            elif instruction & 0xf0ff == 0x6000:
                base = self.pc
                displacement = self.signed_word()
                condition = (instruction >> 8) & 15
                take = {0: True, 6: not self.z, 7: self.z, 11: self.n}[condition]
                if take:
                    self.pc = base + displacement
            elif instruction == 0x3e3c:
                self.d[7] = (self.d[7] & 0xffff0000) | self.fetch()
            elif instruction == 0xb308:  # CMPM.B (A0)+,(A1)+
                self.flags(self.memory[self.a[1]] - self.memory[self.a[0]], 8)
                self.a[0] += 1
                self.a[1] += 1
            elif instruction == 0x51cf:  # DBF D7,d16
                base = self.pc
                displacement = self.signed_word()
                count = (self.d[7] - 1) & 0xffff
                self.d[7] = (self.d[7] & 0xffff0000) | count
                if count != 0xffff:
                    self.pc = base + displacement
            elif instruction == 0x4e41:
                self.trap()
                if self.exit is not None:
                    return self
            else:
                raise AssertionError(f"unexpected opcode {instruction:04x} at {self.pc - 2:06x}")
        raise AssertionError("PRG did not terminate within instruction bound")


def independent_read(image, filename, directory=None):
    # Independently derive BPB offsets and decode FAT12 pairs/chain data.
    bps, spc, reserved, fats, entries, sectors, media, fatsectors = struct.unpack_from("<HBHBHHBH", image, 11)
    rootstart = (reserved + fats * fatsectors) * bps
    data_start = rootstart + ((entries * 32 + bps - 1) // bps) * bps
    directory = image[rootstart:rootstart + entries * 32] if directory is None else directory
    for offset in range(0, len(directory), 32):
        entry = directory[offset:offset + 32]
        if entry[:11] != filename:
            continue
        cluster, length = struct.unpack_from("<HI", entry, 26)
        data, seen = bytearray(), set()
        while cluster < 0xff8:
            assert 2 <= cluster < (sectors * bps - data_start) // (spc * bps) + 2
            assert cluster not in seen
            seen.add(cluster)
            start = data_start + (cluster - 2) * spc * bps
            data.extend(image[start:start + spc * bps])
            start = reserved * bps + (cluster * 3 // 2)
            value = image[start] | (image[start + 1] << 8)
            cluster = value >> 4 if cluster & 1 else value & 0xfff
        return bytes(data) if entry[11] & 16 else bytes(data[:length])
    return None


def capture_with_marker(image, name=b"PASS    TXT", data=diagnostic.PASS_TEXT):
    image = bytearray(image)
    # Place result in the last valid, originally free cluster; write both FATs.
    cluster = 714
    for base in (512, 2048):
        offset = base + cluster * 3 // 2
        pair = image[offset] | (image[offset + 1] << 8)
        pair = (pair & 0xf000) | 0xfff
        image[offset:offset + 2] = struct.pack("<H", pair)
    entry = bytearray(32)
    entry[:11], entry[11] = name, 0x20
    struct.pack_into("<HI", entry, 26, cluster, len(data))
    image[7 * 512 + 64:7 * 512 + 96] = entry
    start = 14 * 512 + (cluster - 2) * 1024
    image[start:start + len(data)] = data
    return bytes(image)


class DiagnosticTests(unittest.TestCase):
    def test_real_emitted_instructions_run_position_independently(self):
        for base in (0x1000, 0x4000, 0x20000):
            with self.subTest(base=base):
                machine = Machine(base=base).run()
                self.assertEqual(machine.exit, 0)
                self.assertEqual(machine.files, {"A:\\PASS.TXT": diagnostic.PASS_TEXT})
                self.assertEqual(machine.console, [diagnostic.PASS_TEXT.decode()])
                calls = machine.calls
                self.assertEqual(sum(fn == 0x40 for fn, _ in calls), 2)
                self.assertEqual(sum(fn == 0x3f for fn, _ in calls), 4)
                self.assertEqual(sum(fn == 0x56 for fn, _ in calls), 1)

    def test_short_error_corrupt_and_eof_results_cannot_produce_pass(self):
        failures = ("short write", "short read", "corrupt read", "trailing byte", "rename", (0x4a, None),
                    (0x3c, "A:\\FESDATA.TMP"), (0x3e, "A:\\FESDATA.TMP"),
                    (0x3d, "A:\\FESDATA.NEW"), (0x41, "A:\\FESDATA.NEW"),
                    (0x40, "A:\\PASS.TXT"), (0x3e, "A:\\PASS.TXT"))
        for failure in failures:
            with self.subTest(failure=failure):
                machine = Machine(failure).run()
                self.assertTrue(machine.injected)
                self.assertEqual(machine.exit, 1)
                self.assertNotIn("A:\\PASS.TXT", machine.files)
                self.assertEqual(machine.files["A:\\FAIL.TXT"], diagnostic.FAIL_TEXT)
                self.assertTrue(machine.console[0].startswith("FAIL GEMDOS "))

    def test_fat12_manual_auto_program_and_nonexecutable_boot(self):
        for auto in (False, True):
            with self.subTest(auto=auto):
                image = diagnostic.build_disk(auto=auto)
                self.assertEqual(len(image), 737280)
                self.assertEqual(image[512:2048], image[2048:3584])
                self.assertNotEqual(sum(struct.unpack(">256H", image[:512])) & 0xffff, 0x1234)
                directory = independent_read(image, b"AUTO       ") if auto else None
                self.assertEqual(independent_read(image, b"DISKTESTPRG", directory), diagnostic.build_prg())
                self.assertEqual(independent_read(image, b"README  TXT"), diagnostic.README)
                self.assertFalse(diagnostic.inspect_capture(image)["marker_pass"])
                passed = capture_with_marker(image)
                self.assertTrue(diagnostic.inspect_capture(passed)["marker_pass"])
                self.assertFalse(diagnostic.inspect_capture(passed)["hardware_acceptance"])

    def test_capture_rejects_wrong_program_bad_geometry_fat_and_cycles(self):
        original = diagnostic.build_disk()
        bad = bytearray(original)
        bad[14 * 512] ^= 1
        with self.assertRaisesRegex(ValueError, "exact diagnostic"):
            diagnostic.inspect_capture(bytes(bad))
        for change in (lambda b: b.__setitem__(12, 0), lambda b: b.__setitem__(2048 + 4, 1)):
            bad = bytearray(original)
            change(bad)
            with self.assertRaises(ValueError):
                diagnostic.inspect_capture(bytes(bad))
        bad = bytearray(original)
        for base in (512, 2048):
            bad[base + 3:base + 5] = struct.pack("<H", 2)  # cluster 2 points to itself
        with self.assertRaisesRegex(ValueError, "cyclic"):
            diagnostic.inspect_capture(bytes(bad))
        for name, text in ((b"PASS    TXT", b"PASS"), (b"FAIL    TXT", diagnostic.FAIL_TEXT),
                           (b"FESDATA TMP", b"leftover")):
            self.assertFalse(diagnostic.inspect_capture(capture_with_marker(original, name, text))["marker_pass"])

    def test_cli_is_deterministic_generates_no_marker_and_inspects_capture(self):
        with tempfile.TemporaryDirectory() as temp:
            image, prg = Path(temp) / "fixture.st", Path(temp) / "DISKTEST.PRG"
            with contextlib.redirect_stdout(io.StringIO()) as output:
                self.assertEqual(diagnostic.main(["--output", str(image), "--prg", str(prg), "--auto"]), 0)
            record = json.loads(output.getvalue())
            self.assertEqual(record["image_sha256"], hashlib.sha256(image.read_bytes()).hexdigest())
            self.assertFalse(record["marker_pass"])
            self.assertEqual(prg.read_bytes(), diagnostic.build_prg())
            self.assertEqual(image.read_bytes(), diagnostic.build_disk(auto=True))
            image.write_bytes(capture_with_marker(image.read_bytes()))
            with contextlib.redirect_stdout(io.StringIO()):
                self.assertEqual(diagnostic.main(["--inspect", str(image)]), 0)


if __name__ == "__main__":
    unittest.main()
