#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate the banked ST YM ROM from Hatari v2.5.0 measured voltage data.

The primary notices are preserved in cores/fes-atari-st/data. Hatari's ordered
axis interpolation rounds each geometric mean before processing the next axis.
Integer nearest square root below is exactly equivalent for these inputs.
"""
import argparse
import ast
import hashlib
import itertools
import json
import math
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / 'cores/fes-atari-st'
OUTPUT = CORE / 'rtl/st_ym_mix_rom.sv'


def rank(a, b, c):
    return a + b * (b + 1) // 2 + c * (c + 1) * (c + 2) // 6


def tables():
    data = CORE / 'data'
    metadata = json.loads((data / 'source.json').read_text())
    for source in metadata['sources']:
        contents = (data / source['file']).read_bytes()
        if hashlib.sha256(contents).hexdigest() != source['sha256']:
            raise ValueError('primary source hash mismatch: ' + source['file'])
    text = re.sub(r'/\*.*?\*/', '', (data / 'ym2149_fixed_vol.h').read_text(), flags=re.S)
    text = text[text.index('{'):text.rindex('}') + 1]
    measured = ast.literal_eval(text.replace('{', '[').replace('}', ']'))
    assert len(measured) == 16 and all(len(x) == 16 and all(len(y) == 16 for y in x) for x in measured)
    t = [[[0] * 32 for _ in range(32)] for _ in range(32)]

    def gm(a, b):
        product = a * b
        lower = math.isqrt(product)
        return lower + (product - lower * lower > lower)

    for c in range(1, 32, 2):
        for b in range(1, 32, 2):
            for a in range(1, 32, 2):
                t[c][b][a] = measured[(c - 1) // 2][(b - 1) // 2][(a - 1) // 2]
            t[c][b][0] = t[c][b][1]
            t[c][b][1] = t[c][b][3]
            t[c][b][3] = gm(t[c][b][1], t[c][b][5])
            for a in range(2, 32, 2):
                t[c][b][a] = gm(t[c][b][a - 1], t[c][b][a + 1])
        for a in range(32):
            t[c][0][a] = t[c][1][a]
            t[c][1][a] = t[c][3][a]
            t[c][3][a] = gm(t[c][1][a], t[c][5][a])
        for b in range(2, 32, 2):
            for a in range(32):
                t[c][b][a] = gm(t[c][b - 1][a], t[c][b + 1][a])
    for b in range(32):
        for a in range(32):
            t[0][b][a] = t[1][b][a]
            t[1][b][a] = t[3][b][a]
            t[3][b][a] = gm(t[1][b][a], t[5][b][a])
    for c in range(2, 32, 2):
        for b in range(32):
            for a in range(32):
                t[c][b][a] = gm(t[c - 1][b][a], t[c + 1][b][a])
    assert t[31][31][31] == 65119
    full = [t[c][b][a] * 32767 // 65119 for c, b, a in itertools.product(range(32), repeat=3)]
    base = [None] * 5984
    for a, b, c in itertools.combinations_with_replacement(range(32), 3):
        address = rank(a, b, c)
        assert base[address] is None
        base[address] = full[(c << 10) | (b << 5) | a]
    assert None not in base
    corrections = []
    for key, value in enumerate(full):
        a, b, c = sorted((key & 31, (key >> 5) & 31, key >> 10))
        difference = value - base[rank(a, b, c)]
        assert difference in (-1, 0, 1)
        if difference:
            corrections.append((key << 1) | (difference > 0))
    assert len(corrections) == 1159
    max_probes = 0
    for key, value in enumerate(full):
        a, b, c = sorted((key & 31, (key >> 5) & 31, key >> 10))
        actual = base[rank(a, b, c)]
        lo, hi, probes = 0, len(corrections), 0
        while lo < hi:
            mid = (lo + hi) // 2
            word = corrections[mid]
            probes += 1
            if word >> 1 == key:
                actual += 1 if word & 1 else -1
                break
            if word >> 1 < key:
                lo = mid + 1
            else:
                hi = mid
        assert actual == value
        max_probes = max(max_probes, probes)
    assert max_probes == 11
    return base, corrections


def render(base, corrections):
    lines = ['// SPDX-License-Identifier: GPL-2.0-or-later',
             '// Generated by scripts/generate_st_ym_mix_rom.py; do not edit.',
             '// Measured by Paulo Simoes (Copyright 2012); Hatari v2.5.0 interpolation.',
             '// See ../data/source.json and ../data/GPL-2.0.txt for primary provenance.',
             '// 5984 canonical values and 1159 signed ordered-key corrections.',
             '// Each bank read and its bank selector register on the same edge.',
             '// Capacity estimate: 15 explicit 512-word banks; mapping is not qualified.',
             'module st_ym_mix_rom (', '    input wire clk,',
             '    input wire [12:0] base_addr,', '    input wire [10:0] correction_addr,',
             '    output wire [14:0] base_data,', '    output wire [15:0] correction_data', ');',
             '    reg [3:0] base_bank;', '    reg [1:0] correction_bank;',
             '    reg base_valid;', '    reg correction_valid;',
             '    wire [14:0] base_words [0:11];', '    wire [15:0] correction_words [0:2];',
             '    always @(posedge clk) begin', '        base_bank <= base_addr[12:9];',
             "        base_valid <= base_addr < 13'd5984;", '        correction_bank <= correction_addr[10:9];',
             "        correction_valid <= correction_addr < 11'd1159;", '    end',
             "    assign base_data = base_valid ? base_words[base_bank] : 15'd0;",
             "    assign correction_data = correction_valid ? correction_words[correction_bank] : 16'd0;"]
    for name, words, width in [('base', base, 15), ('correction', corrections, 16)]:
        for bank in range((len(words) + 511) // 512):
            values = words[bank * 512:(bank + 1) * 512]
            values += [0] * (512 - len(values))
            ident = f'{name}_bank_{bank:02d}'
            lines += [f'    reg [{width-1}:0] {ident} [0:511];',
                      f'    reg [{width-1}:0] {ident}_word;',
                      f'    assign {name}_words[{bank}] = {ident}_word;', '    initial begin']
            lines += [f"        {ident}[{i}] = {width}'h{value:04x};" for i, value in enumerate(values)]
            lines += ['    end', '    always @(posedge clk)',
                      f'        {ident}_word <= {ident}[{name}_addr[8:0]];']
    return '\n'.join(lines + ['endmodule', ''])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='verify generated RTL without writing')
    args = parser.parse_args()
    base, corrections = tables()
    expected = render(base, corrections)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            print('generated ST YM mixer ROM is stale', file=sys.stderr)
            return 1
    else:
        OUTPUT.write_text(expected)
    print('ST YM ROM: 32768 triples verified; 5984 canonical; 1159 corrections; maximum 11 probes; 15 banks')
    return 0


if __name__ == '__main__':
    sys.exit(main())
