package emitcpp

import (
	"fmt"
	"strings"

	"github.com/DeanoC/mister-packages/internal/pack"
)

func Generate(resolved *pack.Resolved) (string, error) {
	symbols, err := resolved.Symbols()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("// Code generated by mister-packages from packages/platform/")
	b.WriteString(resolved.Platform.ID)
	b.WriteString(".yaml.\n")
	b.WriteString("// Do not edit.\n\n")
	b.WriteString("#pragma once\n\n")
	b.WriteString("#include <cstdint>\n\n")
	b.WriteString("namespace mister {\n")
	b.WriteString("namespace native {\n")
	b.WriteString("namespace generated {\n\n")
	for _, symbol := range symbols {
		fmt.Fprintf(&b, "constexpr std::uint32_t %s = 0x%xu;\n", symbol.Name, symbol.Value)
	}
	b.WriteString("\n} // namespace generated\n")
	b.WriteString("} // namespace native\n")
	b.WriteString("} // namespace mister\n")
	return b.String(), nil
}
