package emitcpp

import (
	"fmt"
	"strings"

	"github.com/DeanoC/mister-packages/internal/pack"
)

func Generate(resolved *pack.Resolved) (string, error) {
	symbols, err := resolved.Symbols()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	writeGeneratedPreamble(&b, "packages/platform/"+resolved.Platform.ID+".yaml")
	b.WriteString("#include <cstdint>\n\n")
	b.WriteString("namespace mister {\n")
	b.WriteString("namespace native {\n")
	b.WriteString("namespace generated {\n\n")
	for _, symbol := range symbols {
		fmt.Fprintf(&b, "constexpr std::uint32_t %s = 0x%xu;\n", symbol.Name, symbol.Value)
	}
	b.WriteString("\n} // namespace generated\n")
	b.WriteString("} // namespace native\n")
	b.WriteString("} // namespace mister\n")
	return b.String(), nil
}

func GenerateSystem(sys *pack.SystemFile) (string, error) {
	prefix := cppIdent(sys.ExpectedCore)
	if prefix == "" {
		return "", fmt.Errorf("expected_core %q is not a C++ identifier", sys.ExpectedCore)
	}
	var b strings.Builder
	writeGeneratedPreamble(&b, "packages/system/"+sys.ID+".yaml")
	b.WriteString("// Image layout owns the absolute RBF path; this table owns the artifact name.\n\n")
	b.WriteString("#include <cstddef>\n")
	b.WriteString("#include <cstdint>\n\n")
	b.WriteString("namespace mister {\n")
	b.WriteString("namespace native {\n")
	b.WriteString("namespace generated {\n\n")
	b.WriteString("struct GeneratedMediaRule {\n")
	b.WriteString("  const char* role;\n")
	b.WriteString("  std::uint8_t index;\n")
	b.WriteString("  bool required;\n")
	b.WriteString("  const char* const* extensions;\n")
	b.WriteString("  std::size_t extension_count;\n")
	b.WriteString("  std::uint64_t maximum_size;\n")
	b.WriteString("};\n\n")
	b.WriteString("struct GeneratedCoreRecipe {\n")
	b.WriteString("  std::uint16_t reset_assert_word;\n")
	b.WriteString("  std::uint16_t initial_status_word;\n")
	b.WriteString("  std::uint16_t reset_release_word;\n")
	b.WriteString("  const char* file_wire;\n")
	b.WriteString("};\n\n")
	b.WriteString("struct GeneratedInputRecipe {\n")
	b.WriteString("  std::uint8_t player_count;\n")
	b.WriteString("  std::uint16_t player_command;\n")
	b.WriteString("  std::uint16_t up;\n")
	b.WriteString("  std::uint16_t down;\n")
	b.WriteString("  std::uint16_t left;\n")
	b.WriteString("  std::uint16_t right;\n")
	b.WriteString("  std::uint16_t a;\n")
	b.WriteString("  std::uint16_t b;\n")
	b.WriteString("  std::uint16_t c;\n")
	b.WriteString("  std::uint16_t start;\n")
	b.WriteString("};\n\n")
	b.WriteString("struct GeneratedSystem {\n")
	b.WriteString("  const char* system;\n")
	b.WriteString("  const char* expected_core;\n")
	b.WriteString("  const char* rbf_role;\n")
	b.WriteString("  const char* rbf_artifact;\n")
	b.WriteString("  const GeneratedMediaRule* media;\n")
	b.WriteString("  std::size_t media_count;\n")
	b.WriteString("  GeneratedCoreRecipe core;\n")
	b.WriteString("  GeneratedInputRecipe input;\n")
	b.WriteString("};\n\n")

	for _, rule := range sys.Media {
		name := prefix + cppIdent(rule.Role) + "Extensions"
		fmt.Fprintf(&b, "static constexpr const char* const k%s[] = {", name)
		for i, ext := range rule.Extensions {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(cstring(ext))
		}
		b.WriteString("};\n")
	}
	fmt.Fprintf(&b, "static constexpr GeneratedMediaRule k%sMedia[] = {\n", prefix)
	for _, rule := range sys.Media {
		extName := "k" + prefix + cppIdent(rule.Role) + "Extensions"
		fmt.Fprintf(&b, "    {%s, %d, %s, %s, %d, 0x%xu},\n",
			cstring(rule.Role), rule.Index, boolLit(rule.Required),
			extName, len(rule.Extensions), uint64(rule.MaximumSize))
	}
	b.WriteString("};\n")
	fmt.Fprintf(&b, "static constexpr GeneratedSystem k%s = {\n", prefix)
	fmt.Fprintf(&b, "    %s,\n", cstring(sys.ID))
	fmt.Fprintf(&b, "    %s,\n", cstring(sys.ExpectedCore))
	fmt.Fprintf(&b, "    %s,\n", cstring(sys.RBF.Role))
	fmt.Fprintf(&b, "    %s,\n", cstring(sys.RBF.Artifact))
	fmt.Fprintf(&b, "    k%sMedia,\n", prefix)
	fmt.Fprintf(&b, "    %d,\n", len(sys.Media))
	fmt.Fprintf(&b, "    {0x%x, 0x%x, 0x%x, %s},\n",
		uint64(sys.Core.ResetAssertWord),
		uint64(sys.Core.InitialStatusWord),
		uint64(sys.Core.ResetReleaseWord),
		cstring(sys.Core.FileWire))
	fmt.Fprintf(&b, "    {%d, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x},\n",
		sys.Input.PlayerCount,
		uint64(sys.Input.PlayerCommand),
		uint64(sys.Input.Up),
		uint64(sys.Input.Down),
		uint64(sys.Input.Left),
		uint64(sys.Input.Right),
		uint64(sys.Input.A),
		uint64(sys.Input.B),
		uint64(sys.Input.C),
		uint64(sys.Input.Start))
	b.WriteString("};\n\n")
	b.WriteString("} // namespace generated\n")
	b.WriteString("} // namespace native\n")
	b.WriteString("} // namespace mister\n")
	return b.String(), nil
}

func writeGeneratedPreamble(b *strings.Builder, source string) {
	b.WriteString("// Copyright 2026 FogCast contributors\n")
	b.WriteString("// SPDX-License-Identifier: GPL-3.0-or-later\n\n")
	b.WriteString("// Code generated by mister-packages from ")
	b.WriteString(source)
	b.WriteString(".\n")
	b.WriteString("// Target C++14 (ARMv7 Linux HPS). Do not edit.\n\n")
	b.WriteString("#pragma once\n\n")
}

func cppIdent(value string) string {
	var b strings.Builder
	start := true
	for _, r := range value {
		ok := (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')
		if !ok {
			start = true
			continue
		}
		if start {
			if r >= 'a' && r <= 'z' {
				r = r - 'a' + 'A'
			}
			start = false
		}
		b.WriteRune(r)
	}
	return b.String()
}

func cstring(value string) string {
	replacer := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + replacer.Replace(value) + `"`
}

func boolLit(value bool) string {
	if value {
		return "true"
	}
	return "false"
}
