package emitverilog

import (
	"fmt"
	"strings"

	"github.com/DeanoC/mister-packages/internal/pack"
)

// GenerateFabric uses the existing constant-include format for internal fabric
// contracts. It emits neither RTL modules nor host capability declarations.
func GenerateFabric(fabric *pack.FabricFile) (string, error) {
	if err := fabric.Validate(); err != nil {
		return "", err
	}
	prefix := strings.ToUpper(packageFileName(fabric.ID))
	guard := fmt.Sprintf("%s_CONSTANTS_V%d", prefix, fabric.Major)
	seen := map[string]bool{guard: true}
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by mister-packages from packages/fabric/%s.yaml. Do not edit.\n", packageFileName(fabric.ID))
	fmt.Fprintf(&b, "`ifndef %s\n`define %s\n\n", guard, guard)
	for _, constant := range fabric.Constants {
		name := verilogConstantName(constant.Name)
		if seen[name] {
			return "", fmt.Errorf("fabric %q generates duplicate Verilog macro %q", fabric.ID, name)
		}
		seen[name] = true
		fmt.Fprintf(&b, "`define %s 32'h%08x\n", name, uint64(constant.Value))
	}
	fmt.Fprintf(&b, "\n`endif // %s\n", guard)
	return b.String(), nil
}
