host_os = "linux"
host_arch = "amd64"
image_variant = "native-dev"
version = "0.1.0"
fpga_source = "misteross"
fpga_core = "megadrive"
quartus_version = "17.0.2"

[sources]
FogCast = "cd85971bf0bffe36e69c381917f618620b901726"
libmister-runtime = "443b603de991b56b5f4d0d11c5bc88a3f83fad13"
misteross = "7912a3e7ee82a24c9aed82dfbb30a8974b7eec07"
