#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 FES contributors
"""Firmware page of the open FES Apple II probe card.

The card answers in any physical slot. Its 256-byte `$Cn00` page is
position independent: the caller enters at `$Cn00` with X = slot * 16 and
Y = slot, as the diagnostic's slot scan does. The routine checks the card's
scratch and ID registers through DEVSEL and its `$C800` expansion RAM (the
page access itself claims `$C800` for this card), prints a line through the
diagnostic firmware's PUTS vector and returns A = $A5 on success or $E5.
`$CnF8-$CnFF` holds the signature "FESPROBE". `--verilog` writes the page as
the INIT of the card's 1024x10 M10K.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from asm6502 import assemble  # noqa: E402
from font import screen_code  # noqa: E402

SIGNATURE = b"FESPROBE"
MESSAGE = "PROBE CARD OK IN SLOT "
CARD_ID = 0xA2


def source() -> str:
    message = ", ".join(f"${screen_code(c):02X}" for c in MESSAGE)
    return f"""
SRC     = $0C
SLOT    = $1F
PUTS    = $FE06
PUTC    = $FE0C
        .org $C000
ENTRY:  STY SLOT            ; PUTS uses Y
        LDA #$5A
        STA $C080,X         ; scratch register at $C0n0
        LDA #$00
        LDA $C080,X
        CMP #$5A
        BNE FAIL
        LDA $C081,X         ; card ID
        CMP #${CARD_ID:02X}
        BNE FAIL
        LDA #$C3            ; $C800 RAM, claimed by this page access
        STA $C800
        LDA #$3C
        STA $CBFF
        LDA $C800
        CMP #$C3
        BNE FAIL
        LDA $CBFF
        CMP #$3C
        BNE FAIL
        LDA #<MSG
        STA SRC
        LDA SLOT
        ORA #$C0
        STA SRC+1
        JSR PUTS
        LDA SLOT
        ORA #$B0            ; slot digit
        JSR PUTC
        LDA #$A5
        RTS
FAIL:   LDA #$E5
        RTS
MSG:    .byte {message}, 0
        .org $C0F8
        .byte "FESPROBE"
"""


def page() -> bytes:
    image = assemble(source(), 0xC000, 256, fill=0)
    assert image[0xF8:] == SIGNATURE
    return image


def verilog() -> str:
    words = list(page()) + [0] * (1024 - 256)
    value = 0
    for index, word in enumerate(words):
        value |= word << (index * 10)
    digits = f"{value:02560x}"
    chunks = [digits[offset:offset + 64] for offset in range(0, len(digits), 64)]
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Generated by cores/fes-apple2/diagnostic/probe_card.py; do not edit.",
        "// FES Apple II probe card $Cn00 page as the INIT of a 1024x10 M10K.",
        "localparam [10239:0] PROBE_ROM_INIT = {",
    ]
    for index, chunk in enumerate(chunks):
        lines.append(f"    256'h{chunk}" + ("," if index + 1 < len(chunks) else ""))
    return "\n".join(lines + ["};", ""])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verilog", type=Path, required=True)
    args = parser.parse_args()
    args.verilog.write_text(verilog())


if __name__ == "__main__":
    main()
