"""Check generated consumers and copied Mega Drive source pins without editing them."""
from pathlib import Path
import subprocess
import tempfile
import tomllib
from environment import build_environment

GENERATED = (
    ('emit-go', 'packages/system/megadrive.yaml', 'FogCast', 'internal/systems/generated/megadrive.go'),
    ('emit-cpp', 'packages/system/megadrive.yaml', 'libmister-runtime', 'src/native/generated/megadrive.hpp'),
    ('emit-cpp', 'packages/platform/de10_nano.yaml', 'libmister-runtime', 'src/native/generated/de10_nano.hpp'),
)
CORE_SOURCE = 'packages/source/megadrive_mister.yaml'


def _run(packages, command, source):
    return subprocess.check_output(
        ['go', 'run', './cmd/mister-packages', command, source], cwd=packages,
        env=build_environment())


def check(root: Path, sources: dict[str, Path] | None = None):
    """Validate package YAML, generated bytes, and both copies of the core pin.

    A supplied mapping selects the source trees (including immutable build
    snapshots). No consumer or package file is written.
    """
    root = Path(root)
    if sources is None:
        sources = {name: root / 'sources' / name for name in
                   ('FogCast', 'libmister-runtime', 'misteross', 'mister-packages')}
    sources = {name: Path(path) for name, path in sources.items()}
    packages = sources['mister-packages']
    for source in sorted({item[1] for item in GENERATED} | {CORE_SOURCE}):
        _run(packages, 'validate', source)
    with tempfile.TemporaryDirectory(prefix='fes-generated-') as temporary:
        for index, (command, source, component, destination) in enumerate(GENERATED):
            emitted = Path(temporary) / str(index)
            emitted.write_bytes(_run(packages, command, source))
            consumer = sources[component] / destination
            if emitted.read_bytes() != consumer.read_bytes():
                raise ValueError(f'generated {component}/{destination} differs from mister-packages; regenerate it in the consumer repository')
    # The validated emitter report is a line-oriented key/value representation;
    # YAML parsing and schema validation stay with the package's own Go loader.
    report = {}
    for line in _run(packages, 'report', CORE_SOURCE).decode().splitlines():
        parts = line.split(None, 1)
        if len(parts) != 2 or parts[0] in report:
            raise ValueError('unexpected mister-packages core source report')
        report[parts[0]] = parts[1]
    required = ('repository', 'commit', 'rbf_path', 'rbf_sha256', 'rbf_size', 'project')
    if report.get('core_source') != 'megadrive_mister' or any(key not in report for key in required):
        raise ValueError('incomplete mister-packages core source report')
    report['rbf_size'] = int(report['rbf_size'])
    copies = (
        ('misteross', 'cores.lock', ('core', 'megadrive'),
         {'repository': 'repo', 'commit': 'commit', 'rbf_path': 'rbf_path',
          'rbf_sha256': 'rbf_sha256', 'rbf_size': 'rbf_size', 'project': 'project'}),
        ('FogCast', 'build/native-runtime.inputs.lock.toml', ('megadrive_rbf',),
         {'repository': 'repository', 'commit': 'commit', 'rbf_path': 'path',
          'rbf_sha256': 'sha256', 'rbf_size': 'size'}),
    )
    for component, filename, sections, fields in copies:
        copied = tomllib.loads((sources[component] / filename).read_text())
        for section in sections:
            copied = copied[section]
        for canonical, field in fields.items():
            if copied.get(field) != report[canonical]:
                raise ValueError(f'{component}/{filename}: {field} differs from mister-packages source pin')
    return {'generated_files': len(GENERATED), 'source_pin_copies': len(copies)}


def main():
    try:
        from inputs import validate
        root = Path(__file__).resolve().parents[1]
        validate(root)
        check(root)
    except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as error:
        raise SystemExit(f'consistency: {error}') from error
    print('consistency: package YAML valid; 3 generated consumers and 2 copied source pins match')


if __name__ == '__main__':
    main()
